In [ ]:
#Create the model that can classify the different species of the Iris flower.
#1.create the dataset.
#2.Build the model
#3.Train the model
#4.Make predictions.

In [ ]:
#1.create the dataset.

In [88]:
#iris Dataset
from sklearn.datasets import load_iris
iris= load_iris()
iris.data

#Requirements for working data in scikit-learn
#Features and response are separate objects
#Features and response should be numeric
#Features and response should be numpy Arrays
#Features and reesponse should have specific shapes

iris.feature_names

iris.target

iris.target_names

print(type(iris.data))
print(type(iris.target))


print (iris.data.shape)

print (iris.target.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(150, 4)
(150,)


In [89]:
#2.Build The Model
#Import the class you plan to use -
#Make an instance of the class -
#   Name of the object does not matter
#   can specify tuning parameters (hyperparameters) during this step,
#   All parameters not specified are set to their defaults

In [90]:
#X =features, y= labels
X=iris.data
y=iris.target

# create training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.5)

In [128]:
#KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=8)
print (knn)

#Fit the model
knn.fit(X_train,y_train)

#predict the values
predict1=knn.predict(X_test)

#we can measure accuracy value of predicted with expected value(change value of n_newighbors and chk accuracy again)
from sklearn.metrics import accuracy_score
from sklearn import metrics
print("Accuracy:",accuracy_score(y_test,predict1))

from sklearn.metrics import classification_report,confusion_matrix
print("Confusion Matrix:",confusion_matrix(y_test,predict1))

print(classification_report(y_test,predict1))
knn.score(X_test,y_test)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='uniform')
Accuracy: 0.9733333333333334
Confusion Matrix: [[23  0  0]
 [ 0 24  2]
 [ 0  0 26]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        23
          1       1.00      0.92      0.96        26
          2       0.93      1.00      0.96        26

avg / total       0.98      0.97      0.97        75



0.9733333333333334

In [127]:
# Decision Tree Algorithm
from sklearn import tree
DT = tree.DecisionTreeClassifier()
print(DT)

#Fit the model
DT.fit(X_train,y_train)

#predict the values
predict2=DT.predict(X_test)

#we can measure accuracy value of predicted with expected value
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,predict2))

from sklearn.metrics import classification_report,confusion_matrix
print("Confusion Matrix:",confusion_matrix(y_test,predict2))

print(classification_report(y_test,predict2))
DT.score(X_test,y_test)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
Accuracy: 0.9466666666666667
Confusion Matrix: [[23  0  0]
 [ 0 23  3]
 [ 0  1 25]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        23
          1       0.96      0.88      0.92        26
          2       0.89      0.96      0.93        26

avg / total       0.95      0.95      0.95        75



0.9466666666666667

In [132]:
#SVM Classifier
from sklearn.svm import SVC
svm1 = SVC()

#Fit the model
svm1.fit(X_train,y_train)

#predict the values
predict3 = svm1.predict(X_test)
print(predict3)

#we can measure accuracy value of predicted with expected value
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,predict3))


from sklearn.metrics import classification_report,confusion_matrix
print("Confusion Matrix:",confusion_matrix(y_test,predict3))

print(classification_report(y_test,predict3))
svm1.score(X_test,y_test)

[2 0 2 1 2 2 0 0 0 2 0 2 0 1 0 0 2 2 1 1 1 1 1 1 0 2 0 2 1 0 0 1 1 2 1 1 0
 2 2 0 1 2 2 1 2 0 1 2 2 1 1 1 0 0 1 0 0 2 0 0 0 2 2 0 1 1 2 2 2 2 1 2 2 2
 2]
Accuracy: 0.96
Confusion Matrix: [[23  0  0]
 [ 0 23  3]
 [ 0  0 26]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        23
          1       1.00      0.88      0.94        26
          2       0.90      1.00      0.95        26

avg / total       0.96      0.96      0.96        75



0.96